name: Pacman CI/CD Pipeline

on:
  push:
    branches: [main, test-ci]
  pull_request:
    branches: [main, test-ci]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DISABLE_SOUND: 1
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.11"
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest tests/ --html=report.html
      - name: Upload test report
        uses: actions/upload-artifact@v4.6.1
        with:
          name: test-report
          path: report.html
     

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8-html
      - name: Run Flake8
        run: |
          flake8 --format=html --htmldir=flake8_report
      - name: Upload lint report
        uses: actions/upload-artifact@v4.6.1
        with:
          name: lint-report
          path: flake8_report/index.html
